version: '3.8'

services:
  server:
    image: todo-devserver
    volumes:
      - ./:/usr/src/app
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3004:3004
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=//redis:6379
      - PORT=3004

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mondo_data:/data/db
  redis:
    image: "redis:alpine"
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
    ports:
      - 4567:6379